# Code Generated by Sidekick is for learning and experimentation purposes only.
from models.projects import Project, ProjectStatus
from models.progress import AnalysisConfig
from services.progress_manager import get_progress_manager, cleanup_progress_manager
from services.langgraph_orchestrator import LangGraphOrchestrator


async def run_sde_analysis(project: Project):
    """
    Run comprehensive SDE analysis using LangGraph orchestration
    """
    print(f"\n{'='*60}")
    print(f"🚀 [Orchestrator] Starting LangGraph Analysis")
    print(f"   Project: {project.name} (ID: {project.id})")
    print(f"{'='*60}\n")
    
    # Get progress manager
    progress = get_progress_manager(project)
    
    try:
        # Get or create analysis config
        config = await AnalysisConfig.get_or_none(project=project)
        if not config:
            # Create default config
            config = await AnalysisConfig.create(
                project=project,
                analysis_depth="standard",
                verbosity_level="medium",
                enable_web_search=True,
                generate_diagrams=True,
                analyze_security=True,
                max_parallel_agents=3
            )
        
        await progress.milestone(
            "Starting agent orchestration",
            {
                "depth": config.analysis_depth,
                "web_search": config.enable_web_search,
                "max_agents": config.max_parallel_agents
            }
        )
        
        # Create and run LangGraph orchestrator
        orchestrator = LangGraphOrchestrator(project, config)
        final_state = await orchestrator.run()
        
        # Log completion
        print(f"\n{'='*60}")
        print(f"✅ [Orchestrator] Analysis Complete!")
        print(f"   Messages: {len(final_state.get('messages', []))}")
        print(f"{'='*60}\n")
        
        return final_state
        
    except Exception as e:
        await progress.error(f"Analysis failed: {str(e)}")
        print(f"\n❌ [Orchestrator] Critical failure: {e}")
        import traceback
        traceback.print_exc()
        raise
    finally:
        # Cleanup progress manager
        cleanup_progress_manager(str(project.id))
