# Code Generated by Sidekick is for learning and experimentation purposes only.
from duckduckgo_search import DDGS
from typing import List, Dict
import asyncio


class WebSearchService:
    """
    Service for web-augmented analysis
    """
    def __init__(self):
        self.ddg = DDGS()
    
    async def search(self, query: str, max_results: int = 3) -> List[Dict]:
        """
        Perform web search and return results
        """
        try:
            # Run synchronous search in executor
            loop = asyncio.get_event_loop()
            results = await loop.run_in_executor(
                None,
                lambda: list(self.ddg.text(query, max_results=max_results))
            )
            
            return [
                {
                    'title': r.get('title', ''),
                    'url': r.get('href', ''),
                    'snippet': r.get('body', '')
                }
                for r in results
            ]
        except Exception as e:
            print(f"[WebSearch] Error: {e}")
            return []
    
    async def search_framework_docs(self, framework: str, topic: str) -> List[Dict]:
        """
        Search for framework-specific documentation
        """
        query = f"{framework} {topic} best practices official documentation"
        return await self.search(query)
    
    async def search_security_guidelines(self, topic: str) -> List[Dict]:
        """
        Search for security best practices
        """
        query = f"OWASP {topic} security guidelines best practices"
        return await self.search(query)
    
    async def search_library_patterns(self, library: str, pattern: str) -> List[Dict]:
        """
        Search for library usage patterns
        """
        query = f"{library} {pattern} recommended pattern official docs"
        return await self.search(query)


# Global instance
_web_search = None


def get_web_search() -> WebSearchService:
    """
    Get or create web search service
    """
    global _web_search
    if _web_search is None:
        _web_search = WebSearchService()
    return _web_search
