# Code Generated by Sidekick is for learning and experimentation purposes only.
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from models.users import User
from models.projects import Project
from models.progress import AnalysisConfig
from api.auth import get_current_user

router = APIRouter()


class ConfigRequest(BaseModel):
    analysis_depth: str = "standard"  # quick/standard/deep
    verbosity_level: str = "medium"   # low/medium/high
    enable_web_search: bool = True
    generate_diagrams: bool = True
    analyze_security: bool = True
    analyze_performance: bool = False
    max_parallel_agents: int = 3


class ConfigResponse(BaseModel):
    id: str
    project_id: str
    analysis_depth: str
    verbosity_level: str
    enable_web_search: bool
    generate_diagrams: bool
    analyze_security: bool
    analyze_performance: bool
    max_parallel_agents: int


@router.post("/projects/{project_id}/config", response_model=ConfigResponse)
async def set_analysis_config(
    project_id: str,
    config: ConfigRequest,
    current_user: User = Depends(get_current_user)
):
    """
    Set analysis configuration for a project (before analysis starts)
    """
    project = await Project.get_or_none(id=project_id, user=current_user)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    # Check if config already exists
    existing = await AnalysisConfig.get_or_none(project=project)
    
    if existing:
        # Update existing config
        existing.analysis_depth = config.analysis_depth
        existing.verbosity_level = config.verbosity_level
        existing.enable_web_search = config.enable_web_search
        existing.generate_diagrams = config.generate_diagrams
        existing.analyze_security = config.analyze_security
        existing.analyze_performance = config.analyze_performance
        existing.max_parallel_agents = config.max_parallel_agents
        await existing.save()
        config_obj = existing
    else:
        # Create new config
        config_obj = await AnalysisConfig.create(
            project=project,
            analysis_depth=config.analysis_depth,
            verbosity_level=config.verbosity_level,
            enable_web_search=config.enable_web_search,
            generate_diagrams=config.generate_diagrams,
            analyze_security=config.analyze_security,
            analyze_performance=config.analyze_performance,
            max_parallel_agents=config.max_parallel_agents
        )
    
    return ConfigResponse(
        id=str(config_obj.id),
        project_id=str(project.id),
        analysis_depth=config_obj.analysis_depth,
        verbosity_level=config_obj.verbosity_level,
        enable_web_search=config_obj.enable_web_search,
        generate_diagrams=config_obj.generate_diagrams,
        analyze_security=config_obj.analyze_security,
        analyze_performance=config_obj.analyze_performance,
        max_parallel_agents=config_obj.max_parallel_agents
    )


@router.get("/projects/{project_id}/config", response_model=ConfigResponse)
async def get_analysis_config(
    project_id: str,
    current_user: User = Depends(get_current_user)
):
    """
    Get analysis configuration for a project
    """
    project = await Project.get_or_none(id=project_id, user=current_user)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    config = await AnalysisConfig.get_or_none(project=project)
    
    if not config:
        # Return default config
        return ConfigResponse(
            id="",
            project_id=str(project.id),
            analysis_depth="standard",
            verbosity_level="medium",
            enable_web_search=True,
            generate_diagrams=True,
            analyze_security=True,
            analyze_performance=False,
            max_parallel_agents=3
        )
    
    return ConfigResponse(
        id=str(config.id),
        project_id=str(project.id),
        analysis_depth=config.analysis_depth,
        verbosity_level=config.verbosity_level,
        enable_web_search=config.enable_web_search,
        generate_diagrams=config.generate_diagrams,
        analyze_security=config.analyze_security,
        analyze_performance=config.analyze_performance,
        max_parallel_agents=config.max_parallel_agents
    )
