from fastapi import APIRouter, Depends, UploadFile, File, Form, HTTPException
from typing import List
import json
from models.projects import Project, ProjectStatus
from schemas.project_schema import ProjectCreateResponse
from api.auth import get_current_user
from models.users import User
from services import project_service
from fastapi import BackgroundTasks
from services import analysis_service
from services.analysis_service import preprocess_project, chunk_code, generate_embeddings_for_project
from services.orchestrator import run_sde_analysis  # ADD THIS IMPORT AT TOP OF FILE
# Code Generated by Sidekick is for learning and experimentation purposes only.
from services.progress_manager import get_progress_manager


router = APIRouter()

@router.post("/", response_model=ProjectCreateResponse)
async def create_project(
    background_tasks: BackgroundTasks,
    name: str = Form(...),
    personas: List[str] = Form(...), 
    source_type: str = Form(...),
    github_url: str = Form(None),
    file: UploadFile = File(None),
    current_user: User = Depends(get_current_user)
):
    persona_list = personas
    if source_type == "zip":
        if not file:
            raise HTTPException(status_code=400, detail="ZIP file is required for source_type='zip'")
        project = await project_service.create_project_from_file(name, file, persona_list, current_user)
    
    elif source_type == "github":
        if not github_url:
            raise HTTPException(status_code=400, detail="GitHub URL is required for source_type='github'")
        project = await project_service.create_project_from_github(name, github_url, persona_list, current_user)
    
    else:
        raise HTTPException(status_code=400, detail="Invalid source type. Use 'zip' or 'github'.")

        # Trigger background analysis
    background_tasks.add_task(run_full_analysis, project)
    return project

@router.get("/", response_model=List[ProjectCreateResponse])
async def list_projects(current_user: User = Depends(get_current_user)):
    return await current_user.projects.all()


@router.get("/{project_id}/search")
async def search_code(
    project_id: str, 
    query: str, 
    current_user: User = Depends(get_current_user)
):
    project = await Project.get_or_none(id=project_id, user=current_user)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    # This now returns {"answer": "...", "files": [...]}
    results = await analysis_service.semantic_code_search(project_id, query)
    return results

async def run_full_analysis(project: Project):
    """
    Run complete analysis pipeline with progress tracking
    """
    progress = get_progress_manager(project)
    
    try:
        # Phase 1: Preprocessing
        project.status = ProjectStatus.PREPROCESSING
        await project.save()
        await preprocess_project(project) # Already has progress logic
        
        # Phase 2: Code Chunking
        await progress.milestone("Phase 2: Code Chunking")
        await chunk_code(project.id, progress) # Pass progress
        
        # Phase 3: Generate Embeddings
        await progress.milestone("Phase 3: Generating Embeddings")
        await generate_embeddings_for_project(project.id, progress) # Pass progress
        
        # Phase 4: Agent Analysis (LangGraph)
        project.status = ProjectStatus.PROCESSING
        await project.save()
        await progress.milestone("Phase 4: Agent Analysis")
        await run_sde_analysis(project)
        
        project.status = ProjectStatus.COMPLETED
        await project.save()
        await progress.milestone("All phases complete", {"status": "success"})
        
    except Exception as e:
        project.status = ProjectStatus.FAILED
        project.error_message = str(e)
        await project.save()
        
        await progress.error(f"Analysis failed: {str(e)}")
        print(f"❌ Analysis failed: {e}")
        import traceback
        traceback.print_exc()
