# Code Generated by Sidekick is for learning and experimentation purposes only.
import requests
import json
import websockets

BASE_URL = "http://localhost:8000"

# ========================
# Authentication
# ========================

def login_user(email, password):
    return requests.post(
        f"{BASE_URL}/auth/login",
        data={"username": email, "password": password}
    )

def register_user(email, password):
    return requests.post(
        f"{BASE_URL}/auth/register",
        json={"email": email, "password": password}
    )

# ========================
# Project Management
# ========================

def create_project(token, name, source_type, personas, github_url=None, file=None):
    headers = {"Authorization": f"Bearer {token}"}
    
    payload = [("name", name), ("source_type", source_type)]
    for p in personas:
        payload.append(("personas", p))
    
    if github_url:
        payload.append(("github_url", github_url))
    
    files = None
    if file:
        files = {"file": (file.name, file.getvalue(), "application/zip")}
    
    return requests.post(
        f"{BASE_URL}/projects/",
        headers=headers,
        data=payload,
        files=files
    )

def get_projects(token):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(f"{BASE_URL}/projects/", headers=headers)

def search_project(token, project_id, query):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/projects/{project_id}/search", 
        headers=headers, 
        params={"query": query}
    )

# update search_project to use POST method


# def search_project(token, project_id, query):
#     headers = {"Authorization": f"Bearer {token}"}
#     return requests.post(
#         f"{BASE_URL}/projects/{project_id}/search", 
#         headers=headers,
#         data={"query": query}
#     )

# ========================
# Configuration
# ========================

def get_config(token, project_id):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/config/projects/{project_id}/config",
        headers=headers
    )

def set_config(token, project_id, config_data):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.post(
        f"{BASE_URL}/config/projects/{project_id}/config",
        headers=headers,
        json=config_data
    )

# ========================
# Progress Tracking
# ========================

def get_progress_events(token, project_id, limit=50):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/progress/projects/{project_id}/events",
        headers=headers,
        params={"limit": limit}
    )

def clear_progress_events(token, project_id):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.delete(
        f"{BASE_URL}/progress/projects/{project_id}/events",
        headers=headers
    )

# ========================
# Analysis Results
# ========================

def get_analysis_summary(token, project_id):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/analysis/projects/{project_id}/analysis-summary",
        headers=headers
    )

def get_architecture(token, project_id):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/analysis/projects/{project_id}/architecture",
        headers=headers
    )

def get_api_catalog(token, project_id):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/analysis/projects/{project_id}/api-catalog",
        headers=headers
    )

def get_dependencies(token, project_id):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/analysis/projects/{project_id}/dependencies",
        headers=headers
    )

def get_database_schema(token, project_id):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/analysis/projects/{project_id}/database-schema",
        headers=headers
    )

def get_security_analysis(token, project_id):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/analysis/projects/{project_id}/security",
        headers=headers
    )

def get_setup_guide(token, project_id):
    headers = {"Authorization": f"Bearer {token}"}
    return requests.get(
        f"{BASE_URL}/analysis/projects/{project_id}/setup-guide",
        headers=headers
    )


# Helper to render the event row (kept from your original code)
# Code Generated by Sidekick is for learning and experimentation purposes only.
def get_project_files(token: str, project_id: str, contains_api: bool = None, 
                      contains_db: bool = None, extension: str = None):
    """Get filtered list of project files"""
    params = {}
    if contains_api is not None:
        params['contains_api'] = contains_api
    if contains_db is not None:
        params['contains_db'] = contains_db
    if extension:
        params['extension'] = extension
    
    return requests.get(
        f"{BASE_URL}/analysis/projects/{project_id}/files",
        headers={"Authorization": f"Bearer {token}"},
        params=params
    )
