# Code Generated by Sidekick is for learning and experimentation purposes only.
import asyncio
from wsgiref import headers
import streamlit as st
from api_client import *
import time
import websockets

import streamlit.components.v1 as components

st.set_page_config(
    page_title="HUE Multi-Agent System", 
    layout="wide", 
    page_icon="🏗️"
)

# ========================
# Session State
# ========================

if "token" not in st.session_state:
    st.session_state.token = None
if "selected_project" not in st.session_state:
    st.session_state.selected_project = None
if "monitoring_project" not in st.session_state:
    st.session_state.monitoring_project = None

# ========================
# Helper Functions
# ========================
def render_mermaid(mermaid_code, height=500):
    """Render Mermaid diagram with improved sizing and zoom"""
    html_code = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
        <script>
            mermaid.initialize({{ 
                startOnLoad: true,
                theme: 'dark',
                themeVariables: {{
                    fontSize: '18px',
                    fontFamily: 'Arial, sans-serif'
                }},
                er: {{
                    fontSize: 18,
                    useMaxWidth: false
                }}
            }});
        </script>
        <style>
            * {{
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }}
            body {{
                background-color: #0e1117;
                overflow: auto;
                padding: 20px;
            }}
            .diagram-container {{
                width: 100%;
                display: flex;
                justify-content: center;
                align-items: flex-start;
            }}
            .mermaid {{
                background-color: #1e1e1e;
                padding: 30px;
                border-radius: 10px;
                border: 2px solid #333;
                min-width: 100%;
                transform-origin: top left;
            }}
            /* Make diagram elements larger */
            .mermaid svg {{
                max-width: 1000px !important;
                height: auto !important;
                min-width: 600px;
            }}
            .er.entityBox {{
                font-size: 18px !important;
            }}
            .er.relationshipLabel {{
                font-size: 16px !important;
            }}
        </style>
    </head>
    <body>
        <div class="diagram-container">
            <div class="mermaid">
{mermaid_code}
            </div>
        </div>
    </body>
    </html>
    """
    components.html(html_code, height=height, scrolling=True)

# Code Generated by Sidekick is for learning and experimentation purposes only.
def render_file_card(file):
    """Render a single file card with metadata"""
    with st.container(border=True):
        # File header
        col1, col2 = st.columns([3, 1])
        
        with col1:
            st.markdown(f"**📄 {file['name']}**")
            st.caption(f"`{file['path']}`")
        
        with col2:
            # File size
            size_kb = file.get('size', 0) / 1024
            if size_kb < 1024:
                st.caption(f"💾 {size_kb:.1f} KB")
            else:
                st.caption(f"💾 {size_kb/1024:.1f} MB")
        
        # Badges
        badges = []
        if file.get('is_entry_point'):
            badges.append("🚀 Entry Point")
        if file.get('contains_api_routes'):
            badges.append("🌐 API Routes")
        if file.get('contains_db_models'):
            badges.append("💾 DB Models")
        if file.get('contains_auth'):
            badges.append("🔒 Auth")
        if file.get('is_config_file'):
            badges.append("⚙️ Config")
        
        if badges:
            st.markdown(" ".join([f"`{badge}`" for badge in badges]))
        
        # Imports section
        if file.get('imports'):
            with st.expander("📦 View Imports", expanded=False):
                imports = file['imports']
                for imp in imports:
                    st.code(imp, language="python")


def render_event_item(event):
    icon_map = {
        'milestone': '🎯', 
        'processing': '⚙️', 
        'agent_start': '🤖', 
        'agent_end': '✅', 
        'error': '❌'
    }
    color_map = {
        'milestone': '#28a745', 
        'agent_start': '#ffc107', 
        'error': '#dc3545', 
        'processing': '#17a2b8'
    }
    
    icon = icon_map.get(event['type'], 'ℹ️')
    color = color_map.get(event['type'], '#6c757d')
    
    # Sanitize message to prevent HTML breaking
    msg = str(event.get('message', '')).replace("<", "&lt;").replace(">", "&gt;")
    
    # Parse timestamp
    ts = event.get('timestamp', '')
    if 'T' in ts:
        ts = ts.split('T')[1].split('.')[0]

    # Use a single-line f-string or stripped block to prevent Streamlit markdown parsing issues
    html_code = (
        f'<div style="border-left: 5px solid {color}; '
        f'padding: 10px; margin-bottom: 5px; background-color: #1e1e1e; '
        f'border-radius: 4px; color: #ffffff;">'
        f'<div style="display: flex; justify-content: space-between;">'
        f'<span>{icon} {msg}</span>'
        f'<span style="color: #888; font-size: 0.8em;">{ts}</span>'
        f'</div></div>'
    )
    st.markdown(html_code, unsafe_allow_html=True)


def status_color(status):
    status_map = {
        "completed": "green",
        "ready_for_agents": "blue",
        "processing": "orange",
        "preprocessing": "orange",
        "failed": "red",
        "initialized": "gray"
    }
    return status_map.get(status.lower(), "gray")

def render_metric_card(label, value, icon=""):
    st.markdown(f"""
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                padding: 20px; border-radius: 10px; text-align: center;">
        <h3 style="margin: 0; color: white;">{icon} {value}</h3>
        <p style="margin: 5px 0 0 0; color: rgba(255,255,255,0.8);">{label}</p>
    </div>
    """, unsafe_allow_html=True)

def render_progress_bar(percentage, message=""):
    st.markdown(f"""
    <div style="background: #e9ecef; border-radius: 10px; overflow: hidden; margin: 10px 0;">
        <div style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); 
                    width: {percentage}%; height: 30px; 
                    display: flex; align-items: center; justify-content: center;
                    color: white; font-weight: bold; transition: width 0.3s ease;">
            {percentage:.1f}%
        </div>
    </div>
    <p style="text-align: center; color: #6c757d; margin-top: 5px;">{message}</p>
    """, unsafe_allow_html=True)

def render_severity_badge(severity):
    """Render a colored badge for security severity"""
    colors = {
        "critical": "#dc3545",
        "high": "#fd7e14",
        "medium": "#ffc107",
        "low": "#17a2b8",
        "info": "#6c757d"
    }
    color = colors.get(severity.lower(), "#6c757d")
    return f'<span style="background: {color}; color: white; padding: 3px 10px; border-radius: 12px; font-size: 0.85em; font-weight: bold;">{severity.upper()}</span>'

# ========================
# SIDEBAR
# ========================

if st.session_state.token:
    with st.sidebar:
        st.title("🏗️ HUE System")
        
        page = st.radio(
            "Navigation",
            ["📊 Dashboard", "➕ New Project", "📈 Monitor Progress"],
            label_visibility="collapsed"
        )
        
        st.divider()
        
        if st.button("🚪 Logout", use_container_width=True):
            st.session_state.token = None
            st.session_state.selected_project = None
            st.session_state.monitoring_project = None
            st.rerun()

# ========================
# AUTH PAGE
# ========================

if not st.session_state.token:
    st.markdown("<h1 style='text-align: center;'>🛡️ HUE Access Control</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: gray;'>Intelligence Platform for Software Engineering</p>", unsafe_allow_html=True)
    
    col1, col2, col3 = st.columns([1, 2, 1])
    
    with col2:
        tab1, tab2 = st.tabs(["🔐 Login", "📝 Sign Up"])
        
        with tab1:
            with st.form("login"):
                e = st.text_input("Email", placeholder="engineer@company.com")
                p = st.text_input("Password", type="password")
                
                if st.form_submit_button("Enter System", use_container_width=True, type="primary"):
                    with st.spinner("Authenticating..."):
                        res = login_user(e, p)
                        if res.status_code == 200:
                            st.session_state.token = res.json()["access_token"]
                            st.success("✅ Authentication successful!")
                            st.rerun()
                        else:
                            st.error("❌ Invalid credentials")
        
        with tab2:
            with st.form("signup"):
                ne = st.text_input("Email", placeholder="engineer@company.com")
                np = st.text_input("Password", type="password")
                np2 = st.text_input("Confirm Password", type="password")
                
                if st.form_submit_button("Create Account", use_container_width=True, type="primary"):
                    if np != np2:
                        st.error("Passwords don't match")
                    else:
                        with st.spinner("Creating account..."):
                            res = register_user(ne, np)
                            if res.status_code == 201:
                                st.success("✅ Account created! Please log in.")
                            else:
                                st.error(f"❌ {res.json().get('detail', 'Error creating account')}")

# ========================
# DASHBOARD PAGE
# ========================

elif page == "📊 Dashboard":
    st.title("📊 Project Intelligence Dashboard")
    
    projects_res = get_projects(st.session_state.token)
    
    if projects_res.status_code != 200:
        st.error("Failed to load projects")
    else:
        projs = projects_res.json()
        
        if not projs:
            st.info("🎯 No projects yet. Create your first project to get started!")
        else:
            project_names = {p['name']: p['id'] for p in projs}
            selected_name = st.selectbox(
                "Select Project",
                options=list(project_names.keys()),
                index=0
            )
            selected_id = project_names[selected_name]
            
            project = next(p for p in projs if p['id'] == selected_id)
            
            # Status banner with actions
            status = project['status']
            col1, col2 = st.columns([3, 1])
            
            with col1:
                st.markdown(f"""
                <div style="background-color: {'#d4edda' if status == 'completed' else '#fff3cd'}; 
                            padding: 15px; border-radius: 5px; margin-bottom: 20px;">
                    <strong>Status:</strong> <span style="color: {status_color(status)};">●</span> 
                    {status.replace('_', ' ').title()}
                </div>
                """, unsafe_allow_html=True)
            
            with col2:
                if status in ["processing", "preprocessing"]:
                    if st.button("📈 Monitor Progress", use_container_width=True):
                        st.session_state.monitoring_project = selected_id
                        st.session_state.selected_project = None
                        st.rerun()
            
            # Get analysis summary
            summary_res = get_analysis_summary(st.session_state.token, selected_id)
            summary_data = summary_res.json() if summary_res.status_code == 200 else {}
            
            # Quick metrics
            stats = summary_data.get('statistics', {})
            col1, col2, col3, col4 = st.columns(4)
            with col1:
                render_metric_card("Language", project.get('detected_language', 'N/A'), "💻")
            with col2:
                render_metric_card("Framework", project.get('detected_framework', 'N/A'), "🛠️")
            with col3:
                render_metric_card("Files", stats.get('total_files', 0), "📁")
            with col4:
                render_metric_card("Endpoints", stats.get('api_endpoints', 0), "🌐")
            
            st.divider()
            
            # Analysis tabs (only show when completed)
            if status == "completed":
                tabs = st.tabs([
                    "🏗️ Architecture",
                    "🌐 API Catalog", 
                    "🔗 Dependencies",
                    "💾 Database",
                    "🔒 Security",
                    "📖 Setup Guide",
                    "🔍 Code Search",
                    "📁 Files Explorer"
                ])
                
                # TAB 1: Architecture
                with tabs[0]:
                    st.subheader("🏗️ Architecture Analysis")
                    arch_res = get_architecture(st.session_state.token, selected_id)
                    
                    if arch_res.status_code == 200:
                        arch_data = arch_res.json()
                        
                        # 1. Key Metrics Row
                        m_col1, m_col2, m_col3, m_col4 = st.columns(4)
                        m_col1.metric("Components", arch_data.get('total_components', 0))
                        m_col2.metric("Dependencies", arch_data.get('total_dependencies', 0))
                        m_col3.metric("Framework", arch_data.get('framework', 'N/A'))
                        m_col4.metric("Language", arch_data.get('language', 'N/A'))
                        
                        # 2. Architecture Overview & Pattern
                        if arch_data.get('architecture_overview'):
                            overview = arch_data['architecture_overview']
                            
                            st.markdown(f"### 📐 {overview.get('architecture_pattern', 'Layered')} Architecture")
                            st.info(overview.get('overview', ''))
                            
                            # 3. System Layers
                            if overview.get('layers'):
                                st.markdown("#### 🏛️ System Layers")
                                for layer in overview['layers']:
                                    with st.container(border=True):
                                        st.markdown(f"**{layer['name']}**")
                                        st.caption(layer.get('responsibility', ''))
                                        st.markdown(f"**Components:** " + ", ".join([f"`{c}`" for c in layer.get('components', [])]))

                            # 4. Insights (Strengths & Observations)
                            st.divider()
                            ins_col1, ins_col2 = st.columns(2)
                            with ins_col1:
                                st.markdown("✅ **Strengths**")
                                for strength in overview.get('strengths', []):
                                    st.write(f"- {strength}")
                            
                            with ins_col2:
                                st.markdown("🔬 **Key Observations**")
                                for obs in overview.get('key_observations', []):
                                    st.write(f"- {obs}")

                            # 5. Technology Stack Tags
                            st.markdown("#### 🛠️ Technology Stack")
                            stack_html = " ".join([f'<span style="background-color: #e1e4e8; color: #0366d6; padding: 2px 8px; border-radius: 10px; margin-right: 5px; font-size: 0.8rem;">{t}</span>' for t in overview.get('technology_stack', [])])
                            st.markdown(stack_html, unsafe_allow_html=True)

                            # 6. Improvement Suggestions
                            if overview.get('improvement_suggestions'):
                                with st.expander("💡 Improvement Suggestions"):
                                    for sug in overview['improvement_suggestions']:
                                        st.write(f"- {sug}")

                        # 7. Components Breakdown
                        if arch_data.get('components'):
                            st.divider()
                            st.markdown("### 🧩 Component Breakdown")
                            for comp in arch_data['components']:
                                with st.expander(f"📦 {comp['name']} ({comp['type'].upper()})"):
                                    st.write(f"**Responsibility:** {comp.get('responsibilities', 'N/A')}")
                                    st.write(f"**Files ({comp['file_count']}):**")
                                    # Show first 5 files then a '...' if more exist
                                    display_files = comp['files'][:5]
                                    for f in display_files:
                                        st.caption(f"📄 {f}")
                                    if len(comp['files']) > 5:
                                        st.caption(f"... and {len(comp['files']) - 5} more files")
                    else:
                        st.warning("Architecture analysis not available yet")


                # TAB 2: API Catalog
                with tabs[1]:
                    st.subheader("🌐 API Catalog")
                    api_res = get_api_catalog(st.session_state.token, selected_id)
                    
                    if api_res.status_code == 200:
                        api_data = api_res.json()
                        
                        col1, col2 = st.columns([1, 3])
                        with col1:
                            st.metric("Total Endpoints", api_data.get('total_endpoints', 0))
                        with col2:
                            if api_data.get('catalog'):
                                st.write(api_data['catalog'].get('summary', ''))
                        
                        if api_data.get('endpoints_by_method'):
                            st.markdown("### 📋 Endpoints by HTTP Method")
                            for method, endpoints in api_data['endpoints_by_method'].items():
                                method_color = {
                                    'GET': '#28a745',
                                    'POST': '#007bff',
                                    'PUT': '#ffc107',
                                    'DELETE': '#dc3545',
                                    'PATCH': '#17a2b8'
                                }.get(method, '#6c757d')
                                
                                with st.expander(f"**{method}** ({len(endpoints)} endpoints)", expanded=(method == 'GET')):
                                    for ep in endpoints:
                                        auth_badge = "🔒 Auth Required" if ep.get('requires_auth') else ""
                                        st.markdown(f"""
                                        <div style="border-left: 4px solid {method_color}; padding: 10px; margin: 10px 0; background: #f8f9fa; color: black;">
                                            <strong>{ep['path']}</strong> {auth_badge}<br>
                                            <small>Handler: {ep.get('handler', 'N/A')} | Line: {ep.get('line', 'N/A')}</small><br>
                                            <small>File: {ep.get('file', 'N/A')}</small>
                                        </div>
                                        """, unsafe_allow_html=True)
                    else:
                        st.warning("API catalog not available yet")
                
                # TAB 3: Dependencies
                with tabs[2]:
                    st.subheader("🔗 Dependency Graph")
                    dep_res = get_dependencies(st.session_state.token, selected_id)
                    
                    if dep_res.status_code == 200:
                        dep_data = dep_res.json()
                        stats = dep_data.get('statistics', {})
                        
                        col1, col2, col3 = st.columns(3)
                        with col1:
                            st.metric("Total Files", stats.get('total_files', 0))
                        with col2:
                            st.metric("Dependencies", stats.get('total_dependencies', 0))
                        with col3:
                            st.metric("Circular Deps", stats.get('circular_dependencies', 0))
                        
                        if dep_data.get('circular_dependencies'):
                            st.warning("⚠️ Circular dependencies detected!")
                            for circ in dep_data['circular_dependencies']:
                                st.code(f"{circ['file1']} ⟷ {circ['file2']}")
                        
                        col1, col2 = st.columns(2)
                        
                        with col1:
                            st.markdown("### 📊 Most Dependent Files")
                            for node in stats.get('most_dependent', []):
                                st.write(f"**{node['label']}** - {node['outgoing']} dependencies")
                        
                        with col2:
                            st.markdown("### 📊 Most Depended On")
                            for node in stats.get('most_depended_on', []):
                                st.write(f"**{node['label']}** - {node['incoming']} dependents")
                    else:
                        st.warning("Dependency analysis not available yet")
                
                # TAB 4: Database
                                
               
                                
                # Updated tab code with size controls
                # Code Generated by Sidekick is for learning and experimentation purposes only.
                with tabs[3]:
                    st.subheader("💾 Database Schema")
                    db_res = get_database_schema(st.session_state.token, selected_id)
                    
                    if db_res.status_code == 200:
                        db_data = db_res.json()
                        
                        # Safely get schema_overview with None handling
                        overview = db_data.get('schema_overview') or {}
                        tables = overview.get('tables', []) if overview else []
                        
                        # Top-level metrics
                        col1, col2, col3 = st.columns(3)
                        with col1:
                            total_tables = len(tables)
                            st.metric("Total Tables", total_tables)
                        with col2:
                            st.metric("Framework", db_data.get('framework', 'N/A'))
                        with col3:
                            status = db_data.get('artifact_status', 'unknown')
                            status_emoji = "✅" if status == "completed" else "⏳"
                            if status is not None:
                                st.metric("Status", f"{status_emoji} {status.title()}")
                        
                        # Check if schema_overview exists and is not None
                        if overview and isinstance(overview, dict):
                            # Schema summary
                            if overview.get('summary'):
                                st.info(f"📋 {overview.get('summary')}")
                            
                            if overview.get('relationships_summary'):
                                st.caption(f"🔗 {overview.get('relationships_summary')}")
                            
                            # Display Mermaid ERD diagram if available
                            if overview.get('mermaid_erd'):
                                st.markdown("### 📊 Entity Relationship Diagram")
                                
                                # Add controls
                                col1, col2 = st.columns([3, 1])
                                with col1:
                                    view_option = st.radio(
                                        "View as:",
                                        ["Rendered Diagram", "Mermaid Code"],
                                        horizontal=True,
                                        label_visibility="collapsed"
                                    )
                                with col2:
                                    diagram_height = st.select_slider(
                                        "Height",
                                        options=[600, 800, 1000, 1200, 1500],
                                        value=1000,
                                        label_visibility="collapsed"
                                    )
                                
                                if view_option == "Rendered Diagram":
                                    st.info("💡 Scroll within the diagram to view all tables. Use browser zoom (Ctrl/Cmd +/-) for better readability.")
                                    render_mermaid(overview['mermaid_erd'], height=diagram_height)
                                else:
                                    st.code(overview['mermaid_erd'], language='mermaid')
                                    st.caption("💡 Copy this code to visualize in [Mermaid Live Editor](https://mermaid.live)")
                            
                            # Display tables
                            if tables:
                                st.markdown("### 🗃️ Database Tables")
                                
                                for table in tables:
                                    table_name = table.get('name', 'Unknown')
                                    description = table.get('description', 'No description available')
                                    
                                    with st.expander(f"**{table_name}** - {description}"):
                                        col1, col2 = st.columns(2)
                                        
                                        # Key Fields
                                        with col1:
                                            st.write("**🔑 Key Fields:**")
                                            key_fields = table.get('key_fields', [])
                                            if key_fields:
                                                for field in key_fields:
                                                    st.code(f"• {field}")
                                            else:
                                                st.caption("_No key fields defined_")
                                        
                                        # Relationships
                                        with col2:
                                            st.write("**🔗 Relationships:**")
                                            relationships = table.get('relationships', [])
                                            if relationships:
                                                for rel in relationships:
                                                    if isinstance(rel, dict):
                                                        rel_type = rel.get('type', 'unknown')
                                                        target = rel.get('target', 'unknown')
                                                        st.code(f"{rel_type} → {target}")
                                                    else:
                                                        st.code(str(rel))
                                            else:
                                                st.caption("_No relationships defined_")
                            else:
                                st.info("No tables detected in the schema")
                        else:
                            st.warning("⏳ Schema overview not yet available. The database analysis may still be in progress.")
                        
                        # Optional: Show raw models data if available
                        if db_data.get('models'):
                            with st.expander("🔍 View Raw Models Data"):
                                st.json(db_data['models'])
                        
                        # Models by file (if available)
                        if db_data.get('models_by_file'):
                            st.markdown("### 📁 Models by File")
                            models_by_file = db_data.get('models_by_file')
                            if models_by_file and isinstance(models_by_file, dict):
                                for file_path, models in models_by_file.items():
                                    with st.expander(f"📄 {file_path}"):
                                        st.json(models)
                    
                    elif db_res.status_code == 404:
                        st.warning("⏳ Database schema analysis not started yet. The schema will be available after project analysis completes.")
                    elif db_res.status_code == 202:
                        st.info("⏳ Database schema analysis in progress. Please check back in a moment.")
                    else:
                        st.error(f"❌ Failed to load database schema (Status: {db_res.status_code})")

                
                # TAB 5: Security
                with tabs[4]:
                    st.subheader("🔒 Security Analysis")
                    sec_res = get_security_analysis(st.session_state.token, selected_id)
                    
                    if sec_res.status_code == 200:
                        sec_data = sec_res.json()
                        
                        # 1. Top Level Metrics
                        m_col1, m_col2, m_col3, m_col4 = st.columns(4)
                        counts = sec_data.get('severity_counts', {})
                        
                        m_col1.metric("Total Findings", sec_data.get('total_findings', 0))
                        
                        # Risk Score with color help
                        risk = sec_data.get('risk_score', 0)
                        risk_color = "normal" if risk < 30 else "inverse"
                        m_col2.metric("Risk Score", risk, delta=None, delta_color=risk_color)
                        
                        m_col3.metric("Critical/High", counts.get('critical', 0) + counts.get('high', 0))
                        m_col4.metric("Info/Low", counts.get('info', 0) + counts.get('low', 0))

                        # 2. Authentication Flow (High Value for SDE)
                        if sec_data.get('analysis_overview'):
                            overview = sec_data['analysis_overview']
                            st.markdown("### 🔑 Authentication Architecture")
                            st.info(overview.get('authentication_overview', 'No overview provided.'))
                            
                            auth_flow = overview.get('authentication_flow', {})
                            f_col1, f_col2, f_col3 = st.columns(3)
                            with f_col1:
                                with st.container(border=True):
                                    st.caption("Login Flow")
                                    st.write(auth_flow.get('login', 'N/A'))
                            with f_col2:
                                with st.container(border=True):
                                    st.caption("Registration")
                                    st.write(auth_flow.get('registration', 'N/A'))
                            with f_col3:
                                with st.container(border=True):
                                    st.caption("Token Validation")
                                    st.write(auth_flow.get('token_validation', 'N/A'))

                        # 3. Findings by Severity
                        st.markdown("### 🔍 Security Findings")
                        findings = sec_data.get('findings_by_severity', {})
                        
                        # Severity colors mapping
                        sev_map = {
                            "critical": "🔴",
                            "high": "🟠",
                            "medium": "🟡",
                            "low": "🔵",
                            "info": "⚪"
                        }

                        # Iterate through severities
                        has_findings = False
                        for sev in ['critical', 'high', 'medium', 'low', 'info']:
                            items = findings.get(sev, [])
                            if items:
                                has_findings = True
                                for finding in items:
                                    with st.expander(f"{sev_map[sev]} **{sev.upper()}**: {finding.get('type').replace('_', ' ').title()}"):
                                        st.write(f"**Description:** {finding.get('description')}")
                                        
                                        if finding.get('file_paths'):
                                            st.markdown("**Affected Files:**")
                                            for f in finding['file_paths']:
                                                st.caption(f"📄 `{f}`")
                                        
                                        if finding.get('recommendation'):
                                            st.success(f"**Recommendation:** {finding['recommendation']}")
                                        
                                        # Display CWE/OWASP if available
                                        c1, c2 = st.columns(2)
                                        if finding.get('cwe_id'): c1.caption(f"CWE: {finding['cwe_id']}")
                                        if finding.get('owasp_category'): c2.caption(f"OWASP: {finding['owasp_category']}")

                        if not has_findings:
                            st.success("✅ No security vulnerabilities detected in this codebase.")

                        # 4. Security Features & Best Practices
                        st.divider()
                        b_col1, b_col2 = st.columns(2)
                        
                        with b_col1:
                            st.markdown("🛡️ **Implemented Features**")
                            for feat in overview.get('security_features', []):
                                with st.container(border=True):
                                    st.markdown(f"**{feat['feature']}**")
                                    st.write(feat['implementation'])
                        
                        with b_col2:
                            st.markdown("🌟 **Best Practices Observed**")
                            for bp in overview.get('best_practices_observed', []):
                                st.write(f"✅ {bp}")

                        # 5. Global Recommendations
                        if overview.get('recommendations'):
                            with st.expander("📝 General Security Recommendations"):
                                for rec in overview['recommendations']:
                                    st.write(f"- {rec}")
                                    
                    else:
                        st.warning("Security analysis data is not yet available for this project.")
                
               # TAB 6: Setup Guide
                with tabs[5]:
                    st.subheader("📖 Setup & Installation Guide")
                    setup_res = get_setup_guide(st.session_state.token, selected_id)
                    
                    if setup_res.status_code == 200:
                        setup_data = setup_res.json()
                        guide = setup_data.get('guide', {})

                        # 1. Header Metrics
                        h_col1, h_col2, h_col3, h_col4 = st.columns(4)
                        h_col1.metric("Framework", setup_data.get('framework', 'N/A'))
                        h_col2.metric("Language", setup_data.get('language', 'N/A'))
                        h_col3.metric("Config Files", len(setup_data.get('config_files', [])))
                        entry_point = "undetermined"
                        if setup_data.get('entry_points'):
                            entry_point = setup_data.get('entry_points', [{}])[0].get('name', 'N/A')
                        h_col4.metric("Entry Point", entry_point)

                        # 2. Prerequisites Section
                        if guide.get('prerequisites'):
                            st.markdown("### 📋 Prerequisites")
                            p_cols = st.columns(len(guide['prerequisites']))
                            for idx, prereq in enumerate(guide['prerequisites']):
                                with p_cols[idx % len(p_cols)]:
                                    with st.container(border=True):
                                        st.markdown(f"**{prereq['name']}**")
                                        st.caption(f"Install: {prereq['installation']}")
                                        st.code(prereq['verification'], language="bash")

                        # 3. Installation Steps
                        if guide.get('installation_steps'):
                            st.markdown("### 🔧 Installation Steps")
                            for step in guide['installation_steps']:
                                with st.container(border=True):
                                    st.markdown(f"**Step {step['step']}: {step['title']}**")
                                    st.write(step['description'])
                                    for cmd in step.get('commands', []):
                                        st.code(cmd, language="bash")

                        # 4. Environment & Database
                        st.divider()
                        e_col1, e_col2 = st.columns(2)
                        
                        with e_col1:
                            if guide.get('environment_setup'):
                                env = guide['environment_setup']
                                st.markdown("### 🌍 Environment Setup")
                                st.write(env.get('description', ''))
                                
                                # Construct an example .env content
                                example_env = ""
                                examples = env.get('example_values', {})
                                for var in env.get('required_vars', []):
                                    val = examples.get(var, "your_value_here")
                                    example_env += f"{var}={val}\n"
                                
                                st.markdown("**Example `.env` file:**")
                                st.code(example_env, language="bash")

                        with e_col2:
                            if guide.get('database_setup'):
                                db = guide['database_setup']
                                st.markdown("### 🗄️ Database Setup")
                                for step in db.get('steps', []):
                                    st.write(f"- {step}")
                                for cmd in db.get('commands', []):
                                    st.code(cmd, language="bash")

                        # 5. Running the Application
                        if guide.get('running_the_app'):
                            st.markdown("### 🚀 Running the App")
                            run = guide['running_the_app']
                            r_col1, r_col2 = st.columns(2)
                            
                            with r_col1:
                                dev = run.get('development', {})
                                with st.container(border=True):
                                    st.markdown("**Development Mode**")
                                    st.write(f"Port: `{dev.get('port')}`")
                                    st.code(dev.get('command'), language="bash")
                            
                            with r_col2:
                                prod = run.get('production', {})
                                with st.container(border=True):
                                    st.markdown("**Production Mode**")
                                    st.write(f"Port: `{prod.get('port')}`")
                                    st.code(prod.get('command'), language="bash")

                        # 6. Configuration Files & Troubleshooting
                        st.divider()
                        c_col1, c_col2 = st.columns(2)
                        
                        with c_col1:
                            if setup_data.get('config_files'):
                                with st.expander("⚙️ View All Configuration Files"):
                                    for cfg in setup_data['config_files']:
                                        st.caption(f"`{cfg['name']}` ({cfg['type']})")
                                        st.text(cfg['path'])
                        
                        with c_col2:
                            if guide.get('troubleshooting'):
                                with st.expander("🛠️ Troubleshooting"):
                                    for issue in guide['troubleshooting']:
                                        st.markdown(f"**Issue:** {issue['issue']}")
                                        st.info(f"**Solution:** {issue['solution']}")
                    else:
                        st.warning("Setup guide not available yet")

                # TAB 7: Code Search
                with tabs[6]:
                    st.subheader("🔍 Code Search & AI Analysis")
                    
                    # Use a form to prevent multiple API calls on every keystroke
                    with st.form("search_form"):
                        search_query = st.text_input("Ask about the codebase", 
                                                    placeholder="e.g., How is authentication initialized?")
                        submit_button = st.form_submit_button("Search & Analyze", type="primary", use_container_width=True)
                    
                    if submit_button:
                        if search_query:
                            with st.spinner("🧠 Thinking and analyzing codebase..."):
                                search_res = search_project(st.session_state.token, selected_id, search_query)
                                
                                if search_res.status_code == 200:
                                    data = search_res.json()
                                    
                                    # 1. Display the AI Answer
                                    answer = data.get('answer')
                                    files = data.get('files', [])

                                    if answer:
                                        st.markdown("### 🤖 AI Analysis")
                                        st.info(answer) # Using info box for a distinct background, or st.markdown
                                        st.divider()
                                    
                                    # 2. Display the Source Files
                                    if files:
                                        st.subheader(f"📄 Top {len(files)} Relevant Contexts")
                                        
                                        for idx, result in enumerate(files):
                                            # Create a clean title for the expander
                                            # Handling both Windows and Unix paths
                                            path_str = result.get('file_path', '')
                                            file_name = path_str.replace('\\', '/').split('/')[-1]
                                            chunk_type = result.get('chunk_type', 'Code')
                                            
                                            with st.container(border=True):
                                                # Header: File Path and Relevance Score
                                                col_path, col_score = st.columns([4, 1])
                                                col_path.markdown(f"**{file_name}**")
                                                
                                                # Distance score display (if available)
                                                if result.get('distance'):
                                                    relevance = round((1 - result.get('distance', 0)) * 100, 1)
                                                    col_score.markdown(f"🎯 **{relevance}%** Match")
                                                
                                                st.caption(f"Path: `{path_str}` | Type: `{chunk_type}`")
                                                
                                                # Smart content rendering
                                                content = result.get('content', '')
                                                
                                                # Determine language for highlighting
                                                if path_str.endswith('.md'):
                                                    with st.expander("View Documentation", expanded=False):
                                                        st.markdown(content)
                                                else:
                                                    # Basic language detection logic
                                                    lang = "python"
                                                    if any(path_str.endswith(ext) for ext in [".ts", ".tsx"]): lang = "typescript"
                                                    elif any(path_str.endswith(ext) for ext in [".js", ".jsx"]): lang = "javascript"
                                                    elif path_str.endswith(".yaml") or path_str.endswith(".yml"): lang = "yaml"
                                                    
                                                    st.code(content, language=lang)
                                                
                                                # RRF Rank Score Footer
                                                if result.get('rrf_score'):
                                                    st.caption(f"Rank Score (RRF): {round(result['rrf_score'], 4)}")
                                    else:
                                        st.warning("No relevant code sections were found to back up the answer.")
                                else:
                                    st.error(f"Search failed (Status {search_res.status_code}). Ensure the analysis is complete.")
                        else:
                            st.warning("Please enter a query to search the codebase.")



                # Code Generated by Sidekick is for learning and experimentation purposes only.
                # TAB 8: Files Explorer
                with tabs[7]:
                    st.subheader("📁 Project Files Explorer")
                    
                    # Filter Controls
                    with st.form("file_filters"):
                        st.markdown("#### 🔍 Filter Files")
                        
                        col1, col2, col3 = st.columns(3)
                        
                        with col1:
                            filter_api = st.selectbox(
                                "Contains API Routes",
                                options=[None, True, False],
                                format_func=lambda x: "All" if x is None else ("Yes" if x else "No")
                            )
                        
                        with col2:
                            filter_db = st.selectbox(
                                "Contains DB Models",
                                options=[None, True, False],
                                format_func=lambda x: "All" if x is None else ("Yes" if x else "No")
                            )
                        
                        with col3:
                            # Get unique extensions from the project (you might want to fetch this dynamically)
                            filter_ext = st.text_input(
                                "File Extension",
                                placeholder="e.g., .py, .js, .ts",
                                help="Leave empty for all extensions"
                            )
                        
                        search_button = st.form_submit_button("🔍 Apply Filters", use_container_width=True)
                    
                    # Fetch and display files
                    if search_button or 'files_loaded' not in st.session_state:
                        with st.spinner("Loading files..."):
                            files_res = get_project_files(
                                st.session_state.token,
                                selected_id,
                                contains_api=filter_api,
                                contains_db=filter_db,
                                extension=filter_ext if filter_ext else None
                            )
                            
                            if files_res.status_code == 200:
                                files_data = files_res.json()
                                st.session_state.files_data = files_data
                                st.session_state.files_loaded = True
                            else:
                                st.error(f"Failed to load files (Status: {files_res.status_code})")
                                st.session_state.files_loaded = False
                    
                    # Display results
                    if st.session_state.get('files_loaded'):
                        files_data = st.session_state.files_data
                        
                        # Summary Metrics
                        col1, col2, col3, col4 = st.columns(4)
                        col1.metric("Total Files", files_data.get('total_files', 0))
                        
                        # Count files by type
                        files_list = files_data.get('files', [])
                        api_count = sum(1 for f in files_list if f.get('contains_api_routes'))
                        db_count = sum(1 for f in files_list if f.get('contains_db_models'))
                        config_count = sum(1 for f in files_list if f.get('is_config_file'))
                        
                        col2.metric("API Files", api_count)
                        col3.metric("DB Model Files", db_count)
                        col4.metric("Config Files", config_count)
                        
                        st.divider()
                        
                        # File Categories
                        if files_list:
                            # Group files by category
                            entry_points = [f for f in files_list if f.get('is_entry_point')]
                            api_files = [f for f in files_list if f.get('contains_api_routes') and not f.get('is_entry_point')]
                            db_files = [f for f in files_list if f.get('contains_db_models') and not f.get('is_entry_point')]
                            config_files = [f for f in files_list if f.get('is_config_file')]
                            auth_files = [f for f in files_list if f.get('contains_auth')]
                            other_files = [f for f in files_list if f not in entry_points + api_files + db_files + config_files + auth_files]
                            
                            # Display Entry Points
                            if entry_points:
                                with st.expander(f"🚀 Entry Points ({len(entry_points)})", expanded=True):
                                    for file in entry_points:
                                        render_file_card(file)
                            
                            # Display API Files
                            if api_files:
                                with st.expander(f"🌐 API Route Files ({len(api_files)})", expanded=True):
                                    for file in api_files:
                                        render_file_card(file)
                            
                            # Display Database Files
                            if db_files:
                                with st.expander(f"💾 Database Model Files ({len(db_files)})", expanded=False):
                                    for file in db_files:
                                        render_file_card(file)
                            
                            # Display Auth Files
                            if auth_files:
                                with st.expander(f"🔒 Authentication Files ({len(auth_files)})", expanded=False):
                                    for file in auth_files:
                                        render_file_card(file)
                            
                            # Display Config Files
                            if config_files:
                                with st.expander(f"⚙️ Configuration Files ({len(config_files)})", expanded=False):
                                    for file in config_files:
                                        render_file_card(file)
                            
                            # Display Other Files
                            if other_files:
                                with st.expander(f"📄 Other Files ({len(other_files)})", expanded=False):
                                    for file in other_files:
                                        render_file_card(file)
                        else:
                            st.info("No files found matching the current filters.")

# ========================
# NEW PROJECT PAGE (keep existing code)
# ========================

elif page == "➕ New Project":
    st.title("➕ Create New Project")
    
    if "project_step" not in st.session_state:
        st.session_state.project_step = 1
    
    if st.session_state.project_step == 1:
        st.markdown("### Step 1: Project Details")
                
        p_type = st.radio("Source Type", ["zip", "github"], horizontal=True)

        with st.form("project_details"):
            p_name = st.text_input("Project Name", placeholder="e.g., E-commerce Backend")
            
            # You can still use columns inside the form for other things
            p_personas = st.multiselect("Target Personas", ["SDE", "PM"], default=["SDE"])
            
            gh_url = None
            zip_file = None
            
            # 2. This logic now works because p_type triggers a rerun
            if p_type == "github":
                gh_url = st.text_input("GitHub Repository URL", placeholder="https://github.com/user/repo")
            else:
                zip_file = st.file_uploader("Upload Codebase ZIP", type="zip")
            
            # 3. Submit button stays inside
            if st.form_submit_button("Next: Configure Analysis →", use_container_width=True):
                if not p_name:
                    st.error("Please enter a project name")
                elif p_type == "github" and not gh_url:
                    st.error("Please enter a GitHub URL")
                elif p_type == "zip" and not zip_file:
                    st.error("Please upload a ZIP file")
                else:
                    st.session_state.temp_project = {
                        "name": p_name,
                        "type": p_type,
                        "personas": p_personas,
                        "github_url": gh_url,
                        "zip_file": zip_file
                    }
                    st.session_state.project_step = 2
                    st.rerun()
    
    elif st.session_state.project_step == 2:
        st.markdown("### Step 2: Analysis Configuration")
        
        temp = st.session_state.temp_project
        st.info(f"📁 Project: **{temp['name']}** | Type: **{temp['type']}**")
        
        with st.form("analysis_config"):
            st.markdown("#### Analysis Depth")
            depth = st.select_slider(
                "Choose depth",
                options=["quick", "standard", "deep"],
                value="standard"
            )
            
            st.markdown("#### Documentation Detail")
            verbosity = st.select_slider(
                "Choose verbosity",
                options=["low", "medium", "high"],
                value="medium"
            )
            
            st.markdown("#### Analysis Features")
            col1, col2 = st.columns(2)
            
            with col1:
                web_search = st.checkbox("🌐 Enable Web Search", value=True)
                generate_diagrams = st.checkbox("📊 Generate Diagrams", value=True)
            
            with col2:
                analyze_security = st.checkbox("🔒 Security Analysis", value=True)
                analyze_performance = st.checkbox("⚡ Performance Analysis", value=False)
            
            st.markdown("#### Agent Parallelization")
            max_agents = st.slider("Max Parallel Agents", 1, 5, 3)
            
            col1, col2 = st.columns(2)
            
            with col1:
                if st.form_submit_button("← Back", use_container_width=True):
                    st.session_state.project_step = 1
                    st.rerun()
            
            with col2:
                if st.form_submit_button("🚀 Start Analysis", use_container_width=True, type="primary"):
                    with st.spinner("Creating project..."):
                        res = create_project(
                            st.session_state.token,
                            temp["name"],
                            temp["type"],
                            temp["personas"],
                            temp.get("github_url"),
                            temp.get("zip_file")
                        )
                        
                        if res.status_code == 200:
                            project_data = res.json()
                            project_id = project_data['id']
                            
                            config_data = {
                                "analysis_depth": depth,
                                "verbosity_level": verbosity,
                                "enable_web_search": web_search,
                                "generate_diagrams": generate_diagrams,
                                "analyze_security": analyze_security,
                                "analyze_performance": analyze_performance,
                                "max_parallel_agents": max_agents
                            }
                            
                            config_res = set_config(st.session_state.token, project_id, config_data)
                            
                            if config_res.status_code == 200:
                                st.success(f"✅ Project '{temp['name']}' created!")
                                st.balloons()
                                
                                del st.session_state.temp_project
                                st.session_state.project_step = 1
                                st.session_state.monitoring_project = project_id
                                
                                time.sleep(2)
                                st.rerun()
                        else:
                            st.error(f"❌ {res.json().get('detail', 'Failed')}")

# ========================
# PROGRESS MONITOR PAGE (keep existing code)
# ========================

# Code Generated by Sidekick is for learning and experimentation purposes only.
# Code Generated by Sidekick is for learning and experimentation purposes only.
elif page == "📈 Monitor Progress":
    st.title("📈 System Activity Monitor")
    
    if not st.session_state.monitoring_project:
        st.warning("No project selected. Please go to the Dashboard.")
        if st.button("Go to Dashboard"):
            st.session_state.page = "🏗️ Dashboard"
            st.rerun()
    else:
        project_id = st.session_state.monitoring_project
        
        # Initialize tracking variables for completion detection
        if 'last_event_id' not in st.session_state:
            st.session_state.last_event_id = None
        if 'no_new_events_count' not in st.session_state:
            st.session_state.no_new_events_count = 0
        
        # 1. UI Layout Placeholders
        header_area = st.empty()
        progress_bar_area = st.empty()
        metrics_area = st.empty()
        st.markdown("### 📜 Live Activity Feed")
        
        # Create empty container for feed that can be fully replaced
        feed_area = st.empty()

        # Sidebar config
        st.sidebar.subheader("Monitor Settings")
        refresh_rate = st.sidebar.slider("Polling Interval", 1, 10, 2)
        auto_refresh = st.sidebar.toggle("Auto-Refresh Feed", value=True)
        no_new_events_threshold = st.sidebar.number_input("Mark Complete After (refreshes)", min_value=3, max_value=10, value=5)
        
        if st.sidebar.button("Stop Monitoring"):
            st.session_state.monitoring_project = None
            st.session_state.last_event_id = None
            st.session_state.no_new_events_count = 0
            st.rerun()

        # 2. Continuous Polling Loop
        while auto_refresh:
            try:
                res = get_progress_events(st.session_state.token, project_id)
                
                if res.status_code == 200:
                    events = res.json()
                    
                    if events:
                        latest = events[0]
                        current_event_id = latest.get('id')
                        
                        # Check if we have a new event
                        if current_event_id == st.session_state.last_event_id:
                            # No new events received
                            st.session_state.no_new_events_count += 1
                        else:
                            # New event detected, reset counter
                            st.session_state.last_event_id = current_event_id
                            st.session_state.no_new_events_count = 0
                        
                        # Determine if project is completed
                        is_completed = st.session_state.no_new_events_count >= no_new_events_threshold
                        
                        # --- CYCLING PROGRESS LOGIC ---
                        raw_pct = float(latest.get('percentage', 0))
                        display_pct = raw_pct % 100
                        cycle_number = int(raw_pct // 100)
                        
                        # Update UI with status
                        if is_completed:
                            status_indicator = "🔵 Completed"
                            # Show 100% when completed
                            progress_bar_area.progress(1.0)
                        else:
                            status_indicator = "🟢 Active"
                            progress_bar_area.progress(display_pct / 100.0)
                        
                        header_area.markdown(f"**Target Project:** `{project_id}` | Status: {status_indicator}")
                        
                        with metrics_area:
                            c1, c2, c3 = st.columns(3)
                            c1.metric("Current Stage", latest.get('type', 'N/A').upper())
                            c2.metric("Task Count", f"{latest.get('current_step')}")
                            
                            if is_completed:
                                c3.metric("Status", "✅ Complete")
                            else:
                                progress_label = f"{round(display_pct, 1)}%"
                                if cycle_number > 0:
                                    progress_label += f" (Cycle {cycle_number + 1})"
                                c3.metric("Progress", progress_label)

                        # 3. Render the Feed - Replace old events with latest ones
                        with feed_area.container():
                            # Show completion message if no new events
                            if is_completed:
                                st.success(f"✅ Project processing completed. No new events in last {st.session_state.no_new_events_count} refreshes.")
                                st.divider()
                            
                            # Always show the event history
                            for e in events[:20]:
                                render_event_item(e)
                        
                        # Stop auto-refresh if completed (optional)
                        # Uncomment the next 2 lines if you want monitoring to auto-stop
                        # if is_completed:
                        #     break
                        
                    else:
                        # No events yet, but keep polling
                        header_area.info("System initialized. Waiting for agent activity...")
                        
                elif res.status_code == 404:
                    header_area.error("Project not found. Stopping monitoring.")
                    st.session_state.monitoring_project = None
                    st.session_state.last_event_id = None
                    st.session_state.no_new_events_count = 0
                    break
                elif res.status_code == 401:
                    header_area.error("Authentication failed. Please log in again.")
                    break
                else:
                    header_area.warning(f"API returned status {res.status_code}. Retrying...")
            
            except Exception as e:
                header_area.error(f"Error fetching events: {str(e)}")
                # Continue polling even on error
            
            # Sleep before next poll
            time.sleep(refresh_rate)

