from tortoise import fields, models
from enum import Enum


class ArtifactType(str, Enum):
    ARCHITECTURE_MAP = "architecture_map"
    API_CATALOG = "api_catalog"
    DEPENDENCY_GRAPH = "dependency_graph"
    DATABASE_SCHEMA = "database_schema"
    SECURITY_ANALYSIS = "security_analysis"
    ERROR_HANDLING = "error_handling"
    PERFORMANCE_ANALYSIS = "performance_analysis"
    SETUP_INSTRUCTIONS = "setup_instructions"


class ArtifactStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class AnalysisArtifact(models.Model):
    id = fields.IntField(pk=True)
    project = fields.ForeignKeyField("models.Project", related_name="artifacts")
    artifact_type = fields.CharEnumField(ArtifactType)
    content = fields.JSONField()  # The actual analysis results
    status = fields.CharEnumField(ArtifactStatus, default=ArtifactStatus.PENDING)
    error_message = fields.TextField(null=True)
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)

    class Meta:
        table = "analysis_artifacts"


class ComponentType(str, Enum):
    CONTROLLER = "controller"
    SERVICE = "service"
    MODEL = "model"
    UTILITY = "utility"
    MIDDLEWARE = "middleware"
    REPOSITORY = "repository"
    HELPER = "helper"


class ComponentMetadata(models.Model):
    id = fields.IntField(pk=True)
    project = fields.ForeignKeyField("models.Project", related_name="components")
    component_name = fields.CharField(max_length=255)
    component_type = fields.CharEnumField(ComponentType)
    file_paths = fields.JSONField()  # Array of file paths
    responsibilities = fields.TextField(null=True)  # AI-generated description
    dependencies = fields.JSONField(null=True)  # Which other components it depends on
    created_at = fields.DatetimeField(auto_now_add=True)
    technologies = fields.JSONField(null=True)  

    class Meta:
        table = "component_metadata"


class DependencyType(str, Enum):
    IMPORTS = "imports"
    CALLS = "calls"
    INHERITS = "inherits"
    USES = "uses"


class DependencyEdge(models.Model):
    id = fields.IntField(pk=True)
    project = fields.ForeignKeyField("models.Project", related_name="dependencies")
    source_file = fields.ForeignKeyField("models.FileMetadata", related_name="outgoing_deps")
    target_file = fields.ForeignKeyField("models.FileMetadata", related_name="incoming_deps")
    dependency_type = fields.CharEnumField(DependencyType)
    strength = fields.IntField(default=1)  # How many times this dependency appears
    details = fields.JSONField(null=True)  # Additional context (function names, line numbers)
    created_at = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "dependency_edges"


class APIEndpoint(models.Model):
    id = fields.IntField(pk=True)
    project = fields.ForeignKeyField("models.Project", related_name="endpoints")
    file_metadata = fields.ForeignKeyField("models.FileMetadata", related_name="endpoints")
    method = fields.CharField(max_length=10)  # GET, POST, PUT, DELETE, PATCH
    path = fields.CharField(max_length=500)  # e.g., "/auth/login"
    handler_function = fields.CharField(max_length=255, null=True)  # Function name
    request_schema = fields.JSONField(null=True)
    response_schema = fields.JSONField(null=True)
    requires_auth = fields.BooleanField(default=False)
    description = fields.TextField(null=True)  # AI-generated
    line_number = fields.IntField(null=True)
    created_at = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "api_endpoints"


# Code Generated by Sidekick is for learning and experimentation purposes only.

class SecurityFinding(models.Model):
    id = fields.IntField(pk=True)
    project = fields.ForeignKeyField("models.Project", related_name="security_findings")
    finding_type = fields.CharField(max_length=100)
    file_paths = fields.JSONField()
    code_snippets = fields.JSONField(null=True)
    description = fields.TextField(null=True)
    severity = fields.CharField(max_length=20, null=True)
    recommendation = fields.TextField(null=True)  # ✅ ADD THIS
    cwe_id = fields.CharField(max_length=20, null=True)  # ✅ ADD THIS
    owasp_category = fields.CharField(max_length=100, null=True)  # ✅ ADD THIS
    created_at = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "security_findings"


# Code Generated by Sidekick is for learning and experimentation purposes only.

# Add this after SecurityFinding class:

class DatabaseModel(models.Model):
    id = fields.IntField(pk=True)
    project = fields.ForeignKeyField("models.Project", related_name="database_models")
    file_metadata = fields.ForeignKeyField("models.FileMetadata", related_name="database_models", null=True)
    model_name = fields.CharField(max_length=255)  # e.g., "User", "Product"
    table_name = fields.CharField(max_length=255, null=True)  # Actual database table name
    db_fields = fields.JSONField(null=True)  # Array of field definitions
    relationships = fields.JSONField(null=True)  # Foreign keys, many-to-many, etc.
    indexes = fields.JSONField(null=True)  # Database indexes
    validators = fields.JSONField(null=True)  # Field validators
    description = fields.TextField(null=True)  # AI-generated
    created_at = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "database_models"



