# Code Generated by Sidekick is for learning and experimentation purposes only.
from tortoise import fields
from tortoise.models import Model
from enum import Enum


class EventType(str, Enum):
    """Types of progress events"""
    PROCESSING = "processing"  # File being processed
    MILESTONE = "milestone"     # Major stage completed
    WARNING = "warning"         # Non-critical issue
    ERROR = "error"             # Critical error
    INFO = "info"               # General information
    AGENT_START = "agent_start" # Agent begins work
    AGENT_END = "agent_end"     # Agent completes work
    WEB_SEARCH = "web_search"   # Web search performed


class AnalysisConfig(Model):
    """
    User configuration for analysis behavior
    """
    id = fields.UUIDField(pk=True)
    project = fields.ForeignKeyField("models.Project", related_name="analysis_config")
    
    # Analysis depth
    analysis_depth = fields.CharField(max_length=20, default="standard")  # quick/standard/deep
    
    # Documentation verbosity
    verbosity_level = fields.CharField(max_length=20, default="medium")  # low/medium/high
    
    # Feature toggles
    enable_web_search = fields.BooleanField(default=True)
    generate_diagrams = fields.BooleanField(default=True)
    analyze_security = fields.BooleanField(default=True)
    analyze_performance = fields.BooleanField(default=False)
    
    # Agent-specific settings
    max_parallel_agents = fields.IntField(default=3)
    
    created_at = fields.DatetimeField(auto_now_add=True)
    
    class Meta:
        table = "analysis_configs"


class ProgressEvent(Model):
    """
    Individual progress events during analysis
    """
    id = fields.UUIDField(pk=True)
    project = fields.ForeignKeyField("models.Project", related_name="progress_events")
    
    event_type = fields.CharEnumField(EventType, max_length=20)
    
    # Event details
    message = fields.CharField(max_length=500)
    details = fields.JSONField(null=True)  # Additional context
    
    # Progress tracking
    current_step = fields.IntField(default=0)
    total_steps = fields.IntField(default=0)
    percentage = fields.FloatField(default=0.0)
    
    # Agent information
    agent_name = fields.CharField(max_length=100, null=True)
    
    created_at = fields.DatetimeField(auto_now_add=True)
    
    class Meta:
        table = "progress_events"
        ordering = ["created_at"]
