# Code Generated by Sidekick is for learning and experimentation purposes only.
from models.projects import Project, FileMetadata
from models.analysis import AnalysisArtifact, ArtifactType, ArtifactStatus
from openai import AsyncOpenAI
import os
import json

client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))


async def generate_setup_instructions(project: Project):
    """
    Generate setup instructions for the project
    """
    print(f"📖 [SetupAgent] Generating setup instructions for project {project.id}")
    
    # Get all files in project
    files = await FileMetadata.filter(project=project).all()
    
    # Identify configuration files
    config_files = []
    dependency_files = []
    env_files = []
    docker_files = []
    
    for file in files:
        filename_lower = file.file_name.lower()
        
        # Dependency files
        if filename_lower in ['requirements.txt', 'package.json', 'pyproject.toml', 
                             'pom.xml', 'build.gradle', 'go.mod', 'cargo.toml']:
            dependency_files.append(file)
        
        # Environment files
        elif filename_lower in ['.env.example', '.env.sample', 'config.py', 
                               'settings.py', 'application.properties']:
            env_files.append(file)
        
        # Docker files
        elif filename_lower in ['dockerfile', 'docker-compose.yml', 'docker-compose.yaml']:
            docker_files.append(file)
        
        # Database migration folders
        elif 'migrations' in file.file_path or 'migrate' in file.file_path:
            config_files.append(file)
    
    # Read dependency file contents
    extract_path = f"storage/extracted/{project.id}"
    dependencies_content = ""
    
    for dep_file in dependency_files[:1]:  # Just read the main one
        full_path = os.path.join(extract_path, dep_file.file_path)
        if os.path.exists(full_path):
            with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                dependencies_content = f.read()[:2000]  # Limit size
    
    # Read env example if exists
    env_vars = []
    for env_file in env_files:
        full_path = os.path.join(extract_path, env_file.file_path)
        if os.path.exists(full_path):
            with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
                # Extract env var names
                import re
                env_matches = re.findall(r'^([A-Z_][A-Z0-9_]*)\s*=', content, re.MULTILINE)
                env_vars.extend(env_matches)
    
    # Find entry point
    entry_points = await FileMetadata.filter(
        project=project,
        is_entry_point=True
    ).all()
    
    entry_point_file = entry_points[0].file_name if entry_points else "main.py"
    
    # Generate instructions with LLM
    await generate_setup_guide(
        project=project,
        dependency_files=[f.file_name for f in dependency_files],
        dependencies_content=dependencies_content,
        env_vars=env_vars,
        has_docker=len(docker_files) > 0,
        has_migrations=len(config_files) > 0,
        entry_point=entry_point_file
    )
    
    print(f"✅ [SetupAgent] Generated setup instructions")
    return True


async def generate_setup_guide(project: Project, dependency_files: list, 
                              dependencies_content: str, env_vars: list,
                              has_docker: bool, has_migrations: bool, 
                              entry_point: str):
    """
    Use LLM to generate detailed setup instructions
    """
    prompt = f"""Generate comprehensive setup instructions for this project.

Project: {project.name}
Language: {project.detected_language}
Framework: {project.detected_framework}
Dependency Files: {', '.join(dependency_files)}
Entry Point: {entry_point}
Has Docker: {has_docker}
Has Database Migrations: {has_migrations}
Environment Variables Needed: {', '.join(env_vars[:10])}

Dependencies (sample):
{dependencies_content}

Generate a JSON response with:
{{
  "prerequisites": [
    {{
      "name": "Python 3.14+",
      "installation": "Download from python.org",
      "verification": "python --version"
    }}
  ],
  "installation_steps": [
    {{
      "step": 1,
      "title": "Clone the repository",
      "commands": ["git clone <repo>"],
      "description": "Get the project code"
    }}
  ],
  "environment_setup": {{
    "description": "Configure environment variables",
    "required_vars": ["DATABASE_URL", "SECRET_KEY"],
    "example_values": {{"SECRET_KEY": "generate-secure-key"}}
  }},
  "database_setup": {{
    "steps": ["Create database", "Run migrations"],
    "commands": ["aerich upgrade"]
  }},
  "running_the_app": {{
    "development": {{"command": "uvicorn main:app --reload", "port": 8000}},
    "production": {{"command": "uvicorn main:app", "port": 8000}}
  }},
  "troubleshooting": [
    {{
      "issue": "Port already in use",
      "solution": "Change port or kill existing process"
    }}
  ]
}}

Only respond with valid JSON."""
    
    try:
        response = await client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3
        )
        
        setup_content = response.choices[0].message.content
        
        # Parse JSON
        if "```json" in setup_content:
            setup_content = setup_content.split("```json")[1].split("```")[0].strip()
        elif "```" in setup_content:
            setup_content = setup_content.split("```")[1].split("```")[0].strip()
        
        setup_data = json.loads(setup_content)
        
        # Store in AnalysisArtifact
        await AnalysisArtifact.create(
            project=project,
            artifact_type=ArtifactType.SETUP_INSTRUCTIONS,
            content=setup_data,
            status=ArtifactStatus.COMPLETED
        )
        
        print(f"✅ [SetupAgent] Generated setup guide")
        
    except Exception as e:
        print(f"❌ [SetupAgent] Error generating guide: {e}")
        await AnalysisArtifact.create(
            project=project,
            artifact_type=ArtifactType.SETUP_INSTRUCTIONS,
            content={"error": str(e)},
            status=ArtifactStatus.FAILED,
            error_message=str(e)
        )
